#spring:
#  datasource:
#    username: root
#    password: admin
#    url: jdbc:mysql://127.0.0.1:3306/springbatch?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetriveral=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      schema-locations: classpath:org/springframework/core/schema-mysql.sql
#    mode: never
##    mode: always